<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Ada.API">
        <HintPath>..\..\..\..\..\..\home\a\.nuget\packages\ada.api\6.0.3\lib\net10.0\Ada.API.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ada.Core\Ada.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ada.API\Ada.API.csproj" />
    </ItemGroup>

</Project>
