namespace Ada.Core.Enums.Game.Furniture;

public static class FurnitureItemInteractionType
{
    public const string
        RoomAdsBg = "ads_bg",
        Dimmer = "dimmer",
        Teleport = "teleport",
        Roller = "roller",
        OneWayGate = "onewaygate",
        Gate = "gate",
        VendingMachine = "vending_machine",
        Water = "water",
        WiredTriggerSaysSomething = "wf_trg_says_something",
        WiredTriggerUserWalksOnFurniture = "wf_trg_walks_on_furni",
        WiredTriggerUserWalksOffFurniture = "wf_trg_walks_off_furni",
        WiredTriggerFurnitureStateChanged = "wf_trg_state_changed",
        WiredTriggerEnterRoom = "wf_trg_enter_room",
        WiredEffectShowMessage = "wf_act_show_message",
        WiredEffectKickUser = "wf_act_kick_user",
        WiredEffectTeleportToFurniture = "wf_act_teleport_to",
        WiredEffectMoveRotateFurniture = "wf_act_move_rotate",
        WiredEffectToggleFurnitureState = "wf_act_toggle_state",
        WiredEffectMoveFurnitureToClosestUser = "wf_act_chase",
        WiredEffectMuteTriggerer = "wf_act_mute_triggerer",
        WiredEffectToggleRandomFurnitureState = "wf_xtra_random",
        WiredEffectChangeFurnitureDirection = "wf_act_move_to_dir",
        ClubGate = "club_gate",
        Trophy = "trophy",
        WiredTriggerPeriodically = "wf_trg_period",
        WiredTriggerPeriodicallyLong = "wf_trg_period_long",
        WiredConditionFurnitureHasUsers = "wf_cnd_furnis_hv_avtrs",
        WiredConditionNotFurnitureHasUsers = "wf_cnd_not_furnis_hv_avtrs",
        WiredConditionTriggererOnFurniture = "wf_cnd_actor_on_furni",
        WiredConditionNotTriggererOnFurniture = "wf_cnd_not_on_furni",
        WiredConditionUserCountInRoom = "wf_cnd_user_count_in",
        WiredConditionNotUserCountInRoom = "wf_cnd_not_user_count",
        WiredTriggerAtGivenTime = "wf_trg_at_given_time",
        WiredEffectResetTimers = "wf_act_reset_timers",
        WiredEffectCallAnotherStack = "wf_act_call_stacks",
        WiredEffectFleeFromClosestUser = "wf_act_flee",
        WiredConditionTimeElapsedMore = "wf_cnd_time_more_than",
        WiredConditionTimeElapsedLess = "wf_cnd_time_less_than",
        WiredConditionFurnitureHasFurniture = "wf_cnd_furnis_hv_furnis",
        WiredConditionNotFurnitureHasFurniture = "wf_cnd_not_furnis_hv_furnis",
        WiredConditionTriggererWearsBadge = "wf_cnd_wearing_badge",
        WiredConditionNotTriggererWearsBadge = "wf_cnd_not_wearing_badge",
        WiredConditionTriggererWearsEffect = "wf_cnd_wearing_effect",
        WiredConditionNotTriggererWearsEffect = "wf_cnd_not_wearing_effect",
        WiredConditionTriggererHasHandItem = "wf_cnd_has_handitem",
        WiredConditionDateRangeActive = "wf_cnd_date_rng_active";
}