<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
      <ProjectReference Include="..\Ada.API\Ada.API.csproj" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ada.Db\Ada.Db.csproj" />
        <ProjectReference Include="..\Ada.Networking\Ada.Networking.csproj" />
        <ProjectReference Include="..\Ada.Networking.Writers\Ada.Networking.Writers.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Ada.Tests" />
    </ItemGroup>
</Project>
