namespace Ada.Core.Enums.Miscellaneous;

public enum ChatBubble
{
    Default = 0,
    Respect = 1,
    Bot = 2,
    Red = 3,
    Blue = 4,
    Yellow = 5,
    Green = 6,
    Gray = 7,
    Magic = 8,
    Zombie = 9,
    Skelly = 10,
    SkyBlue = 11,
    Pink = 12,
    Purple = 13,
    Orange = 14,
    AlternativeBlue = 15,
    Valentines = 16,
    RoseBorder = 17,
    Default2 = 18,
    Pig = 19,
    Dog = 20,
    Duck = 21,
    DragonFire = 22,
    Staff = 23,
    Bats = 24,
    Retro = 25,
    SteamPunk = 26,
    Lightning = 27,
    Parrot = 28,
    Pirate = 29,
    Bot2 = 30,
    Bot3 = 31,
    Pirate2 = 32,
    FrankHat = 33,
    Alert = 34,
    Goat = 35,
    Hawaii = 36,
    Administrator = 37,
    Bee = 38
}