<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <RunSettingsFilePath>$(MSBuildProjectDirectory)/coverage.runsettings</RunSettingsFilePath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="NUnit.Analyzers" />
        <PackageReference Include="coverlet.collector" />
        <ProjectReference Include="..\Ada.API\Ada.API.csproj" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ada.Game\Ada.Game.csproj" />
      <ProjectReference Include="..\Ada.Networking\Ada.Networking.csproj" />
      <ProjectReference Include="..\Ada.Networking.Encryption\Ada.Networking.Encryption.csproj" />
      <ProjectReference Include="..\Ada.Networking.Events\Ada.Networking.Events.csproj" />
      <ProjectReference Include="..\Ada.Networking.Writers\Ada.Networking.Writers.csproj" />
      <ProjectReference Include="..\Ada.Server\Ada.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="TestResults\bf946460-637b-45df-9235-c9137f5c5afb\" />
      <Folder Include="TestResults\e2773eb1-4c70-4d9f-8558-d644f352925b\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="TestResults\e2773eb1-4c70-4d9f-8558-d644f352925b\coverage.cobertura.xml" />
    </ItemGroup>

</Project>
